spring.application.name=campus-hub-backend


spring.datasource.url=jdbc:mysql://localhost:3306/campus_hub_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


app.jwt.secret=ThisIsASecretKeyForCampusHubJwtSigningKey1234567890
app.jwt.expiration-ms=86400000

app.admin.name=System Admin
app.admin.email=admin@campushub.com
app.admin.password=Admin123@


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=madhushan437@gmail.com
spring.mail.password=qmqpdrhwggfvxwaz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8088

spring.security.oauth2.client.registration.google.client-id=868375341135-pvqripo9htk8jed2tss8hu67vl2mlof3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

app.frontend.url=http://localhost:5173